name: Docs Report
description: Do the docs need adjustment? Report a bug in the Material for MkDocs documentation.
title: "Docs: "

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: >-
        Please describe the bug you have found in the [Material for MkDocs 
        documentation](https://squidfunk.github.io/mkdocs-material). Explain 
        where the documentation contains a bug or needs improvements, and 
        explain the impact.
        [More](#)
    validations:
      required: true

  - type: textarea
    id: Link-to-the-documentation
    attributes:
      label: Link to the documentation
      description: >-
        Please provide the link to 
        [our documentation](https://squidfunk.github.io/mkdocs-material) where 
        you have found a bug or feel there is a need for more detailed 
        instructions. Additionally, add a screenshot of the specific section.
        [More](#)
      value: |-
        -
    validations:
      required: true

  - type: textarea
    id: improvement-proposals
    attributes:
      label: Improvement proposals
      description: >-
        Please suggest an improvement to our documentation. Provide the 
        suggestion in the text field below or create a pull request containing 
        the issue number.
        [More](#)
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Before submitting
      description: >-
        Please ensure your bug report fulfills all of the following requirements.
        If you need clarification on a specific requirement, follow the link
        to learn about it and understand why it is necessary before ticking the
        box. This will save the maintainers and you valuable time.
      options:
        - label: >-
            I have read and followed the [docs reporting guidelines](#).
          required: true
        - label: >-
            I have attached the links to [the documentation](https://squidfunk.github.io/mkdocs-material), where I have found the bug.
          required: true
        - label: >-
            I have added screenshots showing the bug.
          required: true
        - label: >-
            I have provided an improvement proposal to the best of my knowledge.
          required: true
