name: Docs Report
description: Do the docs need adjustment? Report a bug regarding the Material for MkDocs documentation.
title: "Docs:"

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: >-
        Please describe the bug you have found with the Material for MkDocs 
        documentation. Explain where the documentation contains errors or needs 
        improvements, and explain the impact these errors have.
        [More](#)
    validations:
      required: true

  - type: textarea
    id: Links-to-the-documentation
    attributes:
      label: Links to the documentation
      description: >-
        Please list all links to the sections of 
        [our documentation](https://squidfunk.github.io/mkdocs-material) where
        you have found errors or feel there is a need for more 
        detailed instructions. Include screenshots showing these sections.
        [More](#)
      value: |-
        -
    validations:
      required: true

  - type: textarea
    id: improvement-proposals
    attributes:
      label: Improvement proposals
      description: >-
        Please suggest an improvement to the documentation. This can either be 
        a text you provide here or a pull request, which you provide after 
        posting this issue containing the issue number to help us maintainers to 
        connect the two.
        [More](#)
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Before submitting
      description: >-
        Please ensure your bug report fulfills all of the following requirements.
        If you need clarification on a specific requirement, follow the link
        to learn about it and understand why it is necessary before ticking the
        box. This will save the maintainers and you valuable time.
      options:
        - label: >-
            I have read and followed the [docs reporting guidelines](#).
          required: true
        - label: >-
            I have attached the links to [the documentation](https://squidfunk.github.io/mkdocs-material), where I have found the bug.
          required: true
        - label: >-
            I have added screenshots showing the bug.
          required: true
        - label: >-
            I have provided an improvement proposal to the best of my knowledge.
          required: true
