name: Bug Report
description: Report a bug in Material for MkDocs

body:
  - type: textarea
    attributes:
      label: Context
      description: >-
        This field is optional. You may provide additional context for the bug
        you want to report, helping us to understand what you're working on and
        what you're trying to achieve. If the context is not relevant, you can
        leave this field empty. [More](#)
    validations:
      required: false

  - type: textarea
    attributes:
      label: Bug Description
      description: >-
        Please give a precise description of the bug. Explain where Material
        for MkDocs doesn't behave as you would expect it to. Be as specific as
        possible and tell us (and all other users) if you found a way to work
        around or even fix the problem. [More](#)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Related Links
      description: >-
        Please list all links to the sections of 
        [our documentation](https://squidfunk.github.io/mkdocs-material) that
        are relevant to the bug, in order to show that you have consulted and
        thoroughly read it. Additionally, list links to possibly related issues
        or discussions you encountered when searching our issue tracker.
        [More](#)
      value: |-
        - [Contributing guide](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md)
        - 
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproduction
      description: >-
        Please create a __minimal reproduction__ for the bug. First, read our
        [reproduction guide](#) that explains the necessary steps, then use
        the [built-in info plugin](#) (mandatory) to create a self-contained
        .zip file with the reproduction. Without a reproduction, it can be
        challenging to fix the bug. [More](#)
      placeholder: |-
        Drag and drop .zip file with reproduction here. 
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: >-
        Please provide a detailed list of instructions, guiding us maintainers
        through the required steps to help us recreate the problem using the
        minimal reproduction you provided. Be as specific as possible and as
        verbose as necessary – try not to leave anything out. [More](#)
      placeholder: |-
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: Browser
      description: >-
        If the bug only happens in a __specific browser__, please select it from
        the dropdown below. If your browser is not listed, please select _Other_
        and provide information on the browser you're using as part of the
        context at the top of this issue form. [More](#)
      options:
        - All
        - Chrome
        - Safari
        - Edge
        - Firefox
        - Opera
        - Other
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Before Submitting
      description:  >
        Please ensure your bug report fulfills all of the following requirements.
        If you are not sure what a specific requirement means, follow the link
        to learn and understand why it is necessar before ticking the box.
        This will save the maintainers and you time.
      options:
        - label: I've read and agree with the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md).
          required: true
        - label: I've attached links to [the documentation](#), and related issues or discussions.
          required: true
        - label: I assure that I [removed all customizations](#) before reporting this bug.
          required: true
        - label: I've attached a [minimal reproduction](#).
          required: true
  

