name: Bug Report
description: Report a bug in Material for MkDocs

body:
  - type: textarea
    attributes:
      label: Introduction
      description: >
        This field is optional. You may provide additional context for the bug
        you're about to report, helping us to understand what you're working on
        and what you're trying to achieve.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Bug Description
      description: >
        Please give a precise description of the bug. Explain where Material for
        MkDocs doesn't behave as you would expect. Be as specific as possible.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Links to Documentation
      description: >-
        Please share the links to the specific sections of the Material for 
        MkDocs documentation you were working on when the bug appeared.  
      value: |-
        - [Contributing guide](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md)
        - 
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproducible Example
      description: >-
        Please provide a minimal (!) reproducible example to demonstrate the bug.
        For more information on how to create a reproducible example, see detailed instruction.
      placeholder: |-
        Attach a .zip file here. 
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Step-by-Step Guidance
      description: Please give step-by-step guidance to reproduce the bug.
      placeholder: |-
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: Browser Information
      description: >
        Please choose the browser you have been using in which appeared below.
      options:
        - All
        - Chrome
        - Safari
        - Edge
        - Firefox
        - Opera
        - Other (please explain above)
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Before Submitting
      description:  >
        Please ensure your request fulfills all of the following requirements by **checking all boxes below** before submitting this bug report.
        If one requirement cannot be satisfied, please see (bug report link)
      options:
        - label: I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree.
          required: true
        - label: I've attached a [minimal reproducible example] (link) in a **.zip** file.
          required: true
        - label: I've added [links to the relevant sections] (link) of the Material for MkDocs documentation.
          required: true
        - label: I've checked that the problem persists when all [overrides are removed] (link), i.e. `custom_dir`, `extra_javascript` and `extra_css`.
          required: true
        - label: I've made sure there are **no other open or closed issues** that are related to my bug report.
          required: true
  

