name: Bug Report
description: Report a bug

body:
  - type: textarea
    attributes:
      label: Introductory remarks
      description: >
        Please provide a brief (!) context for the buf or describition of the features you
        were implementing. 
    validations:
      required: false

  - type: textarea
    attributes:
      label: Bug description
      description: >
        Please give a precise description of the bug in 1-2 sentences.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Links to the documentation
      description: >-
        Please share the links to the specific sections in the
        Material for MkDocs documentation you were implementing when the bug appeared.  
      value: |-
        - [Contributing guide](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md)
        - 
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproducible example
      description: >-
        Please provide a minimal (!) reproducible example to 
        demonstrate the bug. Attach a .zip file in the box below. See detailed 
        instruction and provided examples to know how.
      placeholder: |-
        site_name: My Docs
        site_url: https://example.com/docs
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Step by step guidance
      description: Please give a step by step guidance to reproduce the bug.
      placeholder: |-
        1. ...
        2. ...
        3. ...
    validations:
      required: true
 
  - type: textarea
    attributes:
      label: Package versions
      description: Please install the following plugin and copy the output lines.
      value: |-
        - Python: `python --version`
        - MkDocs: `mkdocs --version`
        - Material: `pip show mkdocs-material | grep -E ^Version`
    validations:
      required: true

  - type: textarea
    attributes:
      label: System information
      description: >
        Please provide the your operating system and browser type and version.
      value: |-
        - Operating system: ...
        - Browser: ...
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: hbk
      description:  >
        Please make sure you followed the steps by cheking the boxes below before submitting this bug support.
      options:
        - label: I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree
        - label: I've attached a minimal (!) reproducible example in a .zip file
        - label: I've attached links to the relevanted sections to the Material for MkDocs documentation
        - label: I've checked that the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
        - label: I've made sure there are no open or closed issues that are related to my problem
          required: true
  

