name: Bug Report
description: Report a bug

body:
  - type: textarea
    attributes:
      label: Introductory remarks
      description: >
        (If needed) Please provide a brief context for the bug or a descripition of the features you
        were implementing. 
    validations:
      required: false

  - type: textarea
    attributes:
      label: Bug description
      description: >
        Please give a detailed description of the bug in 1-2 sentences.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Links to the documentation
      description: >-
        Please share the links to the specific sections of the
        Material for MkDocs documentation you were working on when the bug appeared.  
      value: |-
        - [Contributing guide](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md)
        - 
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproducible example
      description: >-
        Please provide a minimal (!) reproducible example to 
        demonstrate the bug. Attach a .zip file in the box below or provide a link to a GitHub repository. See detailed 
        instruction and provided examples to know how.
      placeholder: |-
        site_name: My Docs
        site_url: https://example.com/docs
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Step-by-step guidance
      description: Please give a step by step guidance to reproduce the bug.
      placeholder: |-
        1. ...
        2. ...
        3. ...
    validations:
      required: true
 
  - type: textarea
    attributes:
      label: Package versions
      description: Please install the following plugin and copy the output lines.
      value: |-
        - Python: `python --version`
        - MkDocs: `mkdocs --version`
        - Material: `pip show mkdocs-material | grep -E ^Version`
    validations:
      required: true

  - type: textarea
    attributes:
      label: System information
      description: >
        Please provide your operating system and browser type and version.
      value: |-
        - Operating system: ...
        - Browser: ...
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Before submitting this bug report, I've...
      description:  >
        Please ensure your request fulfills all of the following requirements by **checking all boxes below** before submitting this bug support. If one requirement cannot be satisfied, please see (bug report link)
      options:
        - label: ... read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree
          required: true
        - label: ... attached a [minimal reproducible example] (link) in a **.zip** file
          required: true
        - label: ... added [links to the relevant sections] (link) of the Material for MkDocs documentation
          required: true
        - label: ... checked that the problem persists when all [overrides are removed] (link), i.e. `custom_dir`, `extra_javascript` and `extra_css`
          required: true
        - label: ... made sure there are **no other open or closed issues** that are related to my problem
          required: true
  

