name: Request a change
description: Have a change, feature or improvement suggestion? Submit an idea for Material for MkDocs.

body:
  - type: textarea
    attributes:
      label: Description
      description: >-
        Please provide a detailed description of your idea in 2-3 sentences, so 
        that we maintainers can fully understand what change, feature, or 
        improvement you are proposing.
        [More](#)
    validations:
      required: true

  - type: textarea
    id: related-links
    attributes:
      label: Related links
      description: >-
        Please list all links to [issues](https://github.com/squidfunk/mkdocs-material/issues), 
        [discussions](https://github.com/squidfunk/mkdocs-material/discussions) 
        or to [documentation sections](https://squidfunk.github.io/mkdocs-material) 
        that are relevant to your idea. 
        If you discussed your idea with the community on our 
        [discussion board](https://github.com/squidfunk/mkdocs-material/discussions),
        please link it here.
        [More](#)
      value: |-
        - Issues: 
        - Discussions: 
        - Documentation: 
        - 
    validations:
      required: true

  - type: textarea
    attributes:
      label: Use Cases
      description: >-
       ???? Please explain how your idea will be used by you and the community. 
        Additionally, describe the benefits.




        [More](#)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Idea illustration
      description: >-
        This field is optional. You may provide sketches, screenshots, mockups, 
        or external assets to illustrate your idea. If you have seen this change, 
        feature, or improvement used in other static site generators or themes, 
        please describe how it was used and incorporated.
        [More](#)
      placeholder: |-
        Drag and drop images here or link external assets.

  - type: checkboxes
    attributes:
      label: Before submitting
      description:
        Please ensure your idea fulfills all of the following requirements. If 
        you need clarification on a specific requirement, follow the link to 
        learn about it and understand why it is necessary before ticking the box. 
        This will save the maintainers and you valuable time.
        [More](#)
      options:
      - label: >-
            I have read and followed the [change request guidelines](#).
        required: true
      - label: >-
            I have ensured that, to the best knowledge, my idea will benefit the entire community.
        required: true
      - label: >-
            I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material), related [issues](https://github.com/squidfunk/mkdocs-material/issues)
            or [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.
        required: true
