name: Documentation issue report
description: Does the docs need adjustment? Report your findings in the Material for MkDocs documentation.
labels:
  - documentation

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: >-
        Please describe the inconsitency or issue you have found in the 
        [Material for MkDocs documentation](https://squidfunk.github.io/mkdocs-material) 
        or indicate where you feel there is a need for improvement. Furthermore, 
        explain the impact.
        [More](#)
    validations:
      required: true

  - type: textarea
    id: Link-to-the-documentation
    attributes:
      label: Link to the documentation
      description: >-
        Please link the specific site to [our documentation](https://squidfunk.github.io/mkdocs-material) 
        you described above. If applicable, add screenshots of this specific 
        section.
        [More](#)
      value: |-
        - [Bug reporting](https://squidfunk.github.io/mkdocs-material/bug-report/)
        - Documentation:  
        - 
    validations:
      required: true

  - type: textarea
    id: improvement-proposals
    attributes:
      label: Improvement proposals
      description: >-
        Please provide an improvement proposal for our documentation by describing 
        your suggestion in the text field below or creating a pull request after 
        reporting this issue containing the issue number.
        [More](#)

  - type: checkboxes
    id: checklist
    attributes:
      label: Before submitting
      description: >-
        Please ensure your documentation issue report fulfills all of the 
        following requirements. If you need clarification on a specific 
        requirement, follow the link to learn about it and understand why it is 
        necessary before ticking the box. This will save the maintainers and you 
        valuable time.
        [More](#)
      options:
        - label: >-
            I have read and followed the [documentation issue report guidelines](#).
          required: true
        - label: >-
            I have attached the link to the described section of [the documentation](https://squidfunk.github.io/mkdocs-material)
          required: true
        - label: >-
            I have provided an improvement proposal to the best of my knowledge.
