name: Feature suggestion
description: Have a feature suggestion? Brief an idea for Material for MkDocs.
title: "Feature suggestions: "

body:
  - type: textarea
    attributes:
      label: Description
      description: >-
        Please explain your feature idea for the Material for MkDocs as 
        precisely as possible to us maintainers.
    validations:
      required: true

  - type: textarea
    id: related-links
    attributes:
      label: Related links
      description: >-
        Please link the discussion you started regarding this feature suggestion 
        on our[discussion board](https://github.com/squidfunk/mkdocs-material/discussions).
        Additionally list all possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues), 
        [discussions](https://github.com/squidfunk/mkdocs-material/discussions 
        or relevant sections of [our documentation](https://squidfunk.github.io/mkdocs-material).
        [More](#)
      value: |-
        - Related features in the docs:
        - Discussions:
        - Issues:
    validations:
      required: true

  - type: textarea
    attributes:
      label: Use Cases
      description: >-
        Please explain the use cases of your idea and how your idea  would benefit you and the community
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshots / Mockups
      description: Have you seen this feature somewhere before? If you did, 
        please showcase it with screenshots or provide external assets. If not,
        please build mockups to the best of your ability.
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Before submitting
      description:
        Please ensure your feature suggestion fulfills all of the following 
        requirements. If you need clarification on a specific requirement, 
        follow the link to learn about it and understand why it is necessary 
        before ticking the box. This will save the maintainers and you valuable 
        time.
        [More](#)
      options:
      - label: >-
            I have discussed this feature suggestion in the discussion with the community before opening this form. 
        required: true
      - label: >-
            I have read and followed the [feature suggestion guidelines](#).
        required: true
      - label: >-
            I have made sure that, to my best knowledge, my idea will not break something for the community, other plugins or other themes.
        required: true
      - label: >-
            I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), related [issues](https://github.com/squidfunk/mkdocs-material/issues)
            or [discussions](https://github.com/squidfunk/mkdocs-material/discussions) that are relevant to this feature suggestion
        required: true
