name: Feature suggestion
description: Have a feature suggestion? Brief an idea for Material for MkDocs.
title: "Feature suggestions: "

body:
  - type: textarea
    attributes:
      label: Description
      description: Please describe your idea in a reasonable amount of detail.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Use Cases
      description: Please describe how your idea would benefit you and the community.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshots / Mockups
      description: If applicable, provide mockups or screenshots. You can drag-and-drop images here, or link to external assets.

  - type: checkboxes
    attributes:
      label: Before submitting
      description:
        Please ensure your feature suggestion fulfills all of the following 
        requirements. If you need clarification on a specific requirement, 
        follow the link to learn about it and understand why it is necessary 
        before ticking the box. This will save the maintainers and you valuable 
        time.
        [More](#)
      options:
      - label: >-
            I have read and followed the [feature suggestion guidelines](#).
      - label: I have made sure that, to my best knowledge, my idea will not break something for the community.
      - label: I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material),
            and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues)
            or [discussions](https://github.com/squidfunk/mkdocs-material/discussions) that are relevant to this feature suggestion
      - label: I have provided
