name: Add a translation
description: Missing support for your language? Add a translation
title: Add translations for ...
labels:
  - enhancement
body:

  - type: markdown
    attributes:
      value: |
        > **Warning**: Before creating a new translation, please make sure that 

  - type: textarea
    id: translations
    attributes:
      label: Translations
      description: Please translate the labels on the right, e.g. "Copy to clipboard", etc.
      value: |-
        {% macro t(key) %}{{ {
          "language": "en",
          "direction": "ltr",
          "clipboard.copy": "Copy to clipboard",
          "clipboard.copied": "Copied to clipboard",
          "edit.link.title": "Edit this page",
          "footer.previous": "Previous",
          "footer.next": "Next",
          "footer.title": "Footer",
          "header.title": "Header",
          "meta.comments": "Comments",
          "meta.source": "Source",
          "nav.title": "Navigation",
          "search.placeholder": "Search",
          "search.share": "Share",
          "search.reset": "Clear",
          "search.result.initializer": "Initializing search",
          "search.result.placeholder": "Type to start searching",
          "search.result.none": "No matching documents",
          "search.result.one": "1 matching document",
          "search.result.other": "# matching documents",
          "search.result.more.one": "1 more on this page",
          "search.result.more.other": "# more on this page",
          "search.result.term.missing": "Missing",
          "search.title": "Search",
          "select.language.title": "Select language",
          "select.version.title": "Select version",
          "skip.link.title": "Skip to content",
          "source.link.title": "Go to repository",
          "source.file.date.updated": "Last update",
          "source.file.date.created": "Created",
          "tabs.title": "Tabs",
          "toc.title": "Table of contents",
          "top.title": "Back to top"
        }[key] }}{% endmacro %}
      render: Jinja
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Contribution guidelines
      description: Please read the contribution guidelines before proceeding.
      options:
        - label: I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree
          required: true
