name: Add translation
description: Have a new translation? Add localization for a new language in Material for MkDocs.
title: 'New language:'

body:
  - type: dropdown
    id: browser
    attributes:
      label: Add or update a translation
      description: >-
        
        [More](#)
      multiple: true
      options:
        - Translate
        - Update

  - type: markdown
    attributes:
      value: |
        The following languages are already included:
        <div style="columns: 2; background: red;">
          A<br />
          B
        </div>
        - `af` – Afrikaans
        - `ar` – Arabic
        - `bg` – Bulgarian
        - `bn` – Bengali (Bangla)
        - `ca` – Catalan
        - `cs` – Czech
        - `da` – Danish
        - `de` – German
        - `el` – Greek
        - `en` – English
        - `eo` – Esperanto
        - `es` – Spanish
        - `et` – Estonian
        - `fa` – Persian (Farsi)
        - `fi` – Finnish
        - `fr` – French
        - `gl` – Galician
        - `he` – Hebrew
        - `hi` – Hindi
        - `hr` – Croatian
        - `hu` – Hungarian
        - `hy` – Armenian
        - `id` – Indonesian
        - `is` – Icelandic
        - `it` – Italian
        - `ja` – Japanese
        - `ka` – Georgian
        - `ko` – Korean
        - `lt` – Lithuanian
        - `lv` – Latvian
        - `mk` – Macedonian
        - `mn` – Mongolian
        - `ms` – Bahasa Malaysia
        - `my` – Burmese
        - `nl` – Dutch
        - `nb` – Norwegian (Bokmål)
        - `nn` – Norwegian (Nynorsk)
        - `pl` – Polish
        - `pt` – Portuguese
        - `pt-BR` – Portuguese (Brasilian)
        - `ro` – Romanian
        - `ru` – Russian
        - `sh` – Serbo-Croatian
        - `si` – Sinhalese
        - `sk` – Slovak
        - `sl` – Slovenian
        - `sr` – Serbian
        - `sv` – Swedish
        - `th` – Thai
        - `tl` – Tagalog
        - `tr` – Turkish
        - `uk` – Ukrainian
        - `ur` – Urdu
        - `uz` – Uzbek
        - `vi` – Vietnamese
        - `zh` – Chinese (Simplified)
        - `zh-Hant` – Chinese (Traditional)
        - `zh-TW` – Chinese (Taiwanese)
        - [Add language](?template=bug.yml&steps-to-reproduce=Foo)

  - type: textarea
    attributes:
      label: Translation
      description: Please translate the labels on the right, e.g. "Copy to clipboard", etc.
      value: |-
        {% macro t(key) %}{{ {
          "language": "en",
          "direction": "ltr",
          "clipboard.copy": "Copy to clipboard",
          "clipboard.copied": "Copied to clipboard",
          "edit.link.title": "Edit this page",
          "footer.previous": "Previous",
          "footer.next": "Next",
          "footer.title": "Footer",
          "header.title": "Header",
          "meta.comments": "Comments",
          "meta.source": "Source",
          "nav.title": "Navigation",
          "search.placeholder": "Search",
          "search.share": "Share",
          "search.reset": "Clear",
          "search.result.initializer": "Initializing search",
          "search.result.placeholder": "Type to start searching",
          "search.result.none": "No matching documents",
          "search.result.one": "1 matching document",
          "search.result.other": "# matching documents",
          "search.result.more.one": "1 more on this page",
          "search.result.more.other": "# more on this page",
          "search.result.term.missing": "Missing",
          "search.title": "Search",
          "select.language.title": "Select language",
          "select.version.title": "Select version",
          "skip.link.title": "Skip to content",
          "source.link.title": "Go to repository",
          "source.file.date.updated": "Last update",
          "source.file.date.created": "Created",
          "tabs.title": "Tabs",
          "toc.title": "Table of contents",
          "top.title": "Back to top"
        }[key] }}{% endmacro %}
      render: Jinja
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Contribution guidelines
      description: Please read the contribution guidelines before proceeding.
      options:
        - label: I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree
          required: true

  - type: dropdown
    id: browser
    attributes:
      label: Add or update a translation
      description: >-
        
        [More](#)
      multiple: true
      options:
        - Translate
        - Update

  - type: checkboxes
    attributes:
      label: Language availability
      description: Please ensure that the language you're adding isn't already available.
      options:
        - label: I've checked the [list of available languages](https://bit.ly/33vFDD0)
          required: true
