name: Add a translation
description: Missing support for your language? Add a translation
title: Add translations for ...
labels:
  - change request
body:

  - type: markdown
    attributes:
      value: |-
        **Important**: Before creating a new translation, please make sure that Material for MkDocs does not already include support for your language. Review the list of [available languages](https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/#site-language) and consider contributing missing translations.
        
        _Please note_, that we have grouped languages. To add specific linguistic variations for your country, please add a new language by filling out the following issue and including your country's flag.

  - type: textarea
    id: translations
    attributes:
      label: Translations
      description: >-
        Please translate the labels on the right. For new languages, translate 
        each line. For existing languages, only translate lines containing the 
        icon :arrow_left: and remove the icons before submitting.
        [More](#)
      value: |-
        {% macro t(key) %}{{ {
          "language": "en",
          "direction": "ltr",
          "action.edit": "Edit this page",
          "action.skip": "Skip to content",
          "action.view": "View source of this page",
          "announce.dismiss": "Don't show this again",
          "clipboard.copy": "Copy to clipboard",
          "clipboard.copied": "Copied to clipboard",
          "consent.accept": "Accept",
          "consent.manage": "Manage settings",
          "consent.reject": "Reject",
          "footer": "Footer",
          "footer.next": "Next",
          "footer.previous": "Previous",
          "header": "Header",
          "meta.comments": "Comments",
          "meta.source": "Source",
          "nav": "Navigation",
          "search": "Search",
          "search.placeholder": "Search",
          "search.share": "Share",
          "search.reset": "Clear",
          "search.result.initializer": "Initializing search",
          "search.result.placeholder": "Type to start searching",
          "search.result.none": "No matching documents",
          "search.result.one": "1 matching document",
          "search.result.other": "# matching documents",
          "search.result.more.one": "1 more on this page",
          "search.result.more.other": "# more on this page",
          "search.result.term.missing": "Missing",
          "select.language": "Select language",
          "select.version": "Select version",
          "source": "Go to repository",
          "source.file.date.created": "Created",
          "source.file.date.updated": "Last update",
          "tabs": "Tabs",
          "toc": "Table of contents",
          "top": "Back to top"
        }[key] }}{% endmacro %}
      render: Jinja
    validations:
      required: true

  - type: textarea
    id: country-flag
    attributes:
      label: Country flag icon
      description: >-     
        Please add the flag of your country when adding a new language. Select 
        it on our [Icons, Emojis site](https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#search)
        by entering `flag` in the search field. If your flag is not provided by 
        Twemoji, choose an alternative flag.
        [More](#)
      placeholder: |-
        Post the flag of your country.

  - type: checkboxes
    id: checklist
    attributes:
      label: Before submitting
      description: >-
        Please ensure that your translation fulfills the following requirements.
      options:
        - label: I've checked the list of [available languages](https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/#site-language) for existing translations.
          required: true
        - label: I have ensured that, to the best knowledge, the translations are accurate.
          required: true
        - label: >-
            __Optional__: I want to integrate this translation myself and create a 
            pull request following the [contribution guide](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md).
